name: Tests

on:
  push:
    branches: [master]
  pull_request:

jobs:
  unit-tests:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    name: Unit tests

    steps:
      - name: Checkout ${{ github.sha }}
        uses: actions/checkout@v3

      - name: Run unit tests
        run: |
          bin/setup

