name: Tests

on:
  push:
    branches: [master]
  pull_request:

jobs:
  unit-tests:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    name: Unit tests

    steps:
      - name: Checkout ${{ github.sha }}
        uses: actions/checkout@v3

      - name: Run unit tests
        run: |
          npm install --production --prefix tmp yarn
          tmp/node_modules/yarn/bin/yarn --production install --flat --cache-folder ~/.cache/yarn/gyp_test

